добавлена первая версия базы данных
DuhastMish/BookingParser pull request #6
Opened 2020-10-07 14:01 UTC by Denisovalia

Жизнь говно!

2020-10-07 14:44 UTC, DuhastMish requested changes

2020-10-07 14:44 UTC, DuhastMish commented on data_base_setup.py
> +from sqlalchemy.orm import relationship
Не используется

2020-10-07 14:44 UTC, DuhastMish commented on data_base_setup.py
> +import sys
Не используется

2020-10-07 14:44 UTC, DuhastMish commented on data_base_setup.py
> +    _tablename_ = 'details'
details_id = Column(Integer, ForeignKey('hotels.hotels_id'))

2020-10-07 14:44 UTC, DuhastMish commented on data_base_setup.py
> +
coordinates_id = Column(Integer, ForeignKey('details.details_id'))

2020-10-07 14:44 UTC, DuhastMish commented on data_base_setup.py
> +
important_facilities_id = Column(Integer, ForeignKey('details.details_id'))

2020-10-07 14:44 UTC, DuhastMish commented on data_base_setup.py
> +    neighborhood_structures = Column(String(100), nullable = True)
neighborhood_structures_id = Column(Integer, ForeignKey('details.details_id'))

2020-10-07 14:44 UTC, DuhastMish commented on data_base_setup.py
> +    _tablename_ = 'services_offered'
services_offered_id = Column(Integer, ForeignKey('details.details_id'))

2020-10-07 14:44 UTC, DuhastMish commented on data_base_setup.py
> +    services_offered = Column(String(100), nullable = False)
type_id = Column(Integer, ForeignKey('services_offered.services_offered_id'))

2020-10-07 14:44 UTC, DuhastMish commented on data_base_setup.py
> +    value = Column(String(100), nullable = False)
value_id = Column(Integer, ForeignKey('services_offered.services_offered_id'))

2020-10-07 14:44 UTC, DuhastMish commented on data_base_setup.py
> +engine = create_engine('Y-%m-%d-%H.%M.%S')
engine = create_engine('sqlite:///hotels.db', echo=True)

2020-10-12 15:57 UTC, Denisovalia commented on data_base_setup.py
> +    value = Column(String(100), nullable = False)
Хозяин, а что делать с валью и типом, которые повторяются дальше?))))))))))))))

2020-10-31 21:03 UTC, merged